version: '3.8'
services:
    frontend:
        image: latest
        restart: always
        build:
            dockerfile: Dockerfile
            context: frontend
        ports:
            - "$port_frontend:3000"
      
